version: '3.4'

services:
   db:
      image: apidotnet-db
      command: mysqld --default-authentication-plugin=mysql_native_password
      restart: always
      build:
        context: .
        dockerfile: ApiDotNet/Dockerfile
      environment:  
        TZ: America/Sao_Paulo
        MYSQL_ROOT_PASSWORD: docker
        MYSQL_USER: docker
        MYSQL_PASSWORD: docker
        MYSQL_DATABASE: dotnet
      ports:
        - 3308:3307
      networks:
        - udemy-network

   apidotnet:
    image: apidotnet
    build:
      context: .
      dockerfile: ApiDotNet/Dockerfile
    environment:  
        TZ: America/Sao_Paulo
        ASPNETCORE_ENVIRONMENT: Production
    ports:
      - 7101:80
    depends_on:
      - db
    networks:
      - udemy-network
networks:
  udemy-network:
    driver: bridge